spring:
  application:
    name: hookwatch-api

springdoc:
  api-docs:
    path: /api/v1/openapi.json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    customCssUrl: /swagger-ui/hookwatch-theme.css
    customJs: /swagger-ui/hookwatch-branding.js

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hookwatch
    driver-class-name: org.postgresql.Driver
    username: hookwatch
    password: hookwatch
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/hookwatch
    driver-class-name: org.postgresql.Driver
    username: hookwatch
    password: hookwatch
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
