spring:
  application:
    name: hookwatch-api

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:hookwatch;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/hookwatch
    driver-class-name: org.postgresql.Driver
    username: hookwatch
    password: hookwatch
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080
